name: Desplegar en GitHub Pages

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Prevenir ejecuciones simultáneas conflictivas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Instalar Node.js 🔧
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependencias 📦
        run: npm install

      - name: Compilar aplicación 🚀
        run: npm run build

      - name: Desplegar en GitHub Pages 🌐
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Carpeta generada por Vite
          branch: gh-pages # Rama destino para el hosting de archivos estáticos
